
# Banking Transaction Analytics

## Notebook 1 — Data Loading & Cleaning

**Objective**

- Load multi-table banking dataset
- Validate data quality
- Clean and transform data
- Merge relational tables
- Export analytical dataset

In [9]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
import os
print(os.getcwd())

/drive/notebooks

In [17]:
import os

print(os.listdir())

['01_data_cleaning.ipynb', 'Intro.ipynb', 'Lorenz.ipynb', 'Untitled.ipynb', 'accounts.csv', 'branches.csv', 'combined_dementia_dataset.csv', 'customers.csv', 'merchants.csv', 'sqlite.ipynb', 'transactions.csv', 'cpp-tiny-ray-tracer.ipynb', 'cpp.ipynb', 'r.ipynb', 'cpp-third-party-libs.ipynb']

In [18]:
customers = pd.read_csv("customers.csv")
accounts = pd.read_csv("accounts.csv")
transactions = pd.read_csv("transactions.csv")
merchants = pd.read_csv("merchants.csv")
branches = pd.read_csv("branches.csv")
print("loaded successfully")

loaded successfully

In [19]:
datasets = {
    "Customers": customers,
    "Accounts": accounts,
    "Transactions": transactions,
    "Merchants": merchants,
    "Branches": branches
}

for name, df in datasets.items():
    print(f"{name:15} Rows: {df.shape[0]:6} | Columns: {df.shape[1]}")

Customers       Rows:   5000 | Columns: 8
Accounts        Rows:   6200 | Columns: 7
Transactions    Rows: 100000 | Columns: 13
Merchants       Rows:    120 | Columns: 5
Branches        Rows:     25 | Columns: 4

In [22]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        100000 non-null  str
 1   account_id            100000 non-null  str
 2   merchant_id           100000 non-null  str
 3   branch_id             100000 non-null  str
 4   transaction_datetime  100000 non-null  str
 5   transaction_type      100000 non-null  str
 6   amount                100000 non-null  float64
 7   payment_method        100000 non-null  str
 8   channel               100000 non-null  str
 9   opening_balance       100000 non-null  float64
 10  closing_balance       100000 non-null  float64
 11  status                100000 non-null  str
 12  reference_no          100000 non-null  str
dtypes: float64(3), str(10)
memory usage: 6.1 MB

In [26]:
transactions["transaction_datetime"] = pd.to_datetime(
    transactions["transaction_datetime"]
)

print("Date converted successfully!")

Date converted successfully!

In [27]:
transactions["transaction_datetime"].head()

0   2025-12-18 22:48:00
1   2025-05-18 10:37:00
2   2026-04-13 02:32:00
3   2025-06-12 18:22:00
4   2026-05-01 16:42:00
Name: transaction_datetime, dtype: datetime64[us]

transactions.info()

In [28]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        100000 non-null  str
 1   account_id            100000 non-null  str
 2   merchant_id           100000 non-null  str
 3   branch_id             100000 non-null  str
 4   transaction_datetime  100000 non-null  datetime64[us]
 5   transaction_type      100000 non-null  str
 6   amount                100000 non-null  float64
 7   payment_method        100000 non-null  str
 8   channel               100000 non-null  str
 9   opening_balance       100000 non-null  float64
 10  closing_balance       100000 non-null  float64
 11  status                100000 non-null  str
 12  reference_no          100000 non-null  str
dtypes: datetime64[us](1), float64(3), str(9)
memory usage: 6.5 MB

transactions.head()

In [29]:
transactions.head()

,transaction_id,account_id,merchant_id,branch_id,transaction_datetime,transaction_type,amount,payment_method,channel,opening_balance,closing_balance,status,reference_no
0,TXN0000001,ACC002975,MER104,BR025,2025-12-18 22:48:00,Debit,4086.42,UPI,Mobile Banking,85557.75,81471.33,Success,REF9729789661
1,TXN0000002,ACC004775,MER002,BR023,2025-05-18 10:37:00,Credit,1793.55,UPI,Internet Banking,105884.92,107678.47,Success,REF9434640177
2,TXN0000003,ACC005627,MER009,BR019,2026-04-13 02:32:00,Debit,9547.04,NEFT,Internet Banking,336343.50,326796.46,Success,REF2889483864
3,TXN0000004,ACC002167,MER006,BR005,2025-06-12 18:22:00,Debit,764.22,UPI,ATM,96423.36,95659.14,Success,REF4676695532
4,TXN0000005,ACC005845,MER085,BR010,2026-05-01 16:42:00,Debit,2599.33,Debit Card,Mobile Banking,46877.06,44277.73,Success,REF1725477974

In [30]:
# Preview all datasets

tables = {
    "Customers": customers,
    "Accounts": accounts,
    "Transactions": transactions,
    "Merchants": merchants,
    "Branches": branches
}

for name, df in tables.items():
    print("="*50)
    print(name)
    print("="*50)
    display(df.head(3))

==================================================
Customers
==================================================

,customer_id,name,gender,age,occupation,annual_income,city,join_date
0,CUST00001,Rahul Jain,Female,34,Manager,2030985,Patna,2019-05-11
1,CUST00002,Ananya Mehta,Female,23,Student,115457,Ahmedabad,2020-05-27
2,CUST00003,Vivaan Ranjan,Female,54,Engineer,999318,Patna,2019-03-24

==================================================
Accounts
==================================================

,account_id,customer_id,account_type,balance,credit_limit,status,opened_date
0,ACC000001,CUST00001,Savings,142512.75,0,Inactive,2020-04-13
1,ACC000002,CUST00002,Savings,97887.78,0,Active,2025-08-29
2,ACC000003,CUST00003,Savings,92091.22,0,Active,2021-01-21

==================================================
Transactions
==================================================

,transaction_id,account_id,merchant_id,branch_id,transaction_datetime,transaction_type,amount,payment_method,channel,opening_balance,closing_balance,status,reference_no
0,TXN0000001,ACC002975,MER104,BR025,2025-12-18 22:48:00,Debit,4086.42,UPI,Mobile Banking,85557.75,81471.33,Success,REF9729789661
1,TXN0000002,ACC004775,MER002,BR023,2025-05-18 10:37:00,Credit,1793.55,UPI,Internet Banking,105884.92,107678.47,Success,REF9434640177
2,TXN0000003,ACC005627,MER009,BR019,2026-04-13 02:32:00,Debit,9547.04,NEFT,Internet Banking,336343.50,326796.46,Success,REF2889483864

==================================================
Merchants
==================================================

  merchant_id merchant_name  category  mcc_code    city
0      MER001        Amazon  Shopping      5311    Pune
1      MER002      Flipkart  Shopping      5311   Surat
2      MER003        Myntra  Shopping      5651  Bhopal

==================================================
Branches
==================================================

  branch_id       branch_name       city region
0     BR001    Chennai Branch    Chennai  South
1     BR002  Bengaluru Branch  Bengaluru  South
2     BR003  Hyderabad Branch  Hyderabad  South

In [ ]:
#Summary report

In [31]:
summary = []

for name, df in tables.items():

    summary.append({
        "Table": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    })

quality_summary = pd.DataFrame(summary)

quality_summary

          Table    Rows  Columns  Missing Values  Duplicate Rows
0     Customers    5000        8               0               0
1      Accounts    6200        7               0               0
2  Transactions  100000       13               0               0
3     Merchants     120        5               0               0
4      Branches      25        4               0               0

In [32]:
# Validate promary keys - Banking dataset cannot have duplicate ids
primary_keys = {
    "Customers": ("customer_id", customers),
    "Accounts": ("account_id", accounts),
    "Transactions": ("transaction_id", transactions),
    "Merchants": ("merchant_id", merchants),
    "Branches": ("branch_id", branches)
}

pk_report = []

for table, (pk, df) in primary_keys.items():

    pk_report.append({
        "Table": table,
        "Primary Key": pk,
        "Duplicates": df[pk].duplicated().sum(),
        "Missing": df[pk].isnull().sum()
    })

pd.DataFrame(pk_report)

          Table     Primary Key  Duplicates  Missing
0     Customers     customer_id           0        0
1      Accounts      account_id           0        0
2  Transactions  transaction_id           0        0
3     Merchants     merchant_id           0        0
4      Branches       branch_id           0        0

In [33]:
#validate foreign keys
invalid_accounts = transactions[
    ~transactions["account_id"].isin(accounts["account_id"])
]

print("Invalid Account IDs :", len(invalid_accounts))

Invalid Account IDs : 0

In [34]:
''' same as left join
SELECT *
FROM transactions t
LEFT JOIN accounts a
ON t.account_id = a.account_id
WHERE a.account_id IS NULL;
'''


invalid_merchants = transactions[
    ~transactions["merchant_id"].isin(merchants["merchant_id"])
]

invalid_branches = transactions[
    ~transactions["branch_id"].isin(branches["branch_id"])
]

print("Invalid Merchant IDs :", len(invalid_merchants))
print("Invalid Branch IDs :", len(invalid_branches))

Invalid Merchant IDs : 0
Invalid Branch IDs : 0

## Data Integration

We combine all relational tables into one analytical dataset using LEFT JOIN.

In [35]:
master = transactions.merge(
    accounts,
    on="account_id",
    how="left"
)

master.head()

,transaction_id,account_id,merchant_id,branch_id,transaction_datetime,transaction_type,amount,payment_method,channel,opening_balance,closing_balance,status_x,reference_no,customer_id,account_type,balance,credit_limit,status_y,opened_date
0,TXN0000001,ACC002975,MER104,BR025,2025-12-18 22:48:00,Debit,4086.42,UPI,Mobile Banking,85557.75,81471.33,Success,REF9729789661,CUST02975,Savings,85557.75,0,Active,2024-02-22
1,TXN0000002,ACC004775,MER002,BR023,2025-05-18 10:37:00,Credit,1793.55,UPI,Internet Banking,105884.92,107678.47,Success,REF9434640177,CUST04775,Savings,105884.92,0,Active,2024-09-05
2,TXN0000003,ACC005627,MER009,BR019,2026-04-13 02:32:00,Debit,9547.04,NEFT,Internet Banking,336343.50,326796.46,Success,REF2889483864,CUST00539,Savings,336343.50,0,Active,2023-08-12
3,TXN0000004,ACC002167,MER006,BR005,2025-06-12 18:22:00,Debit,764.22,UPI,ATM,96423.36,95659.14,Success,REF4676695532,CUST02167,Current,96423.36,0,Active,2023-08-25
4,TXN0000005,ACC005845,MER085,BR010,2026-05-01 16:42:00,Debit,2599.33,Debit Card,Mobile Banking,46877.06,44277.73,Success,REF1725477974,CUST02405,Current,46877.06,0,Active,2023-01-22

In [36]:
master = master.merge(
    customers,
    on="customer_id",
    how="left"
)

master.head()

,transaction_id,account_id,merchant_id,branch_id,transaction_datetime,transaction_type,amount,payment_method,channel,opening_balance,...,credit_limit,status_y,opened_date,name,gender,age,occupation,annual_income,city,join_date
0,TXN0000001,ACC002975,MER104,BR025,2025-12-18 22:48:00,Debit,4086.42,UPI,Mobile Banking,85557.75,...,0,Active,2024-02-22,Rohit Mehta,Female,54,Designer,445724,Bengaluru,2025-02-28
1,TXN0000002,ACC004775,MER002,BR023,2025-05-18 10:37:00,Credit,1793.55,UPI,Internet Banking,105884.92,...,0,Active,2024-09-05,Rohit Iyer,Female,51,Analyst,865371,Kochi,2024-04-13
2,TXN0000003,ACC005627,MER009,BR019,2026-04-13 02:32:00,Debit,9547.04,NEFT,Internet Banking,336343.50,...,0,Active,2023-08-12,Aman Gupta,Female,34,Doctor,2423909,Kochi,2025-04-17
3,TXN0000004,ACC002167,MER006,BR005,2025-06-12 18:22:00,Debit,764.22,UPI,ATM,96423.36,...,0,Active,2023-08-25,Ananya Reddy,Female,28,Engineer,1595354,Noida,2023-12-11
4,TXN0000005,ACC005845,MER085,BR010,2026-05-01 16:42:00,Debit,2599.33,Debit Card,Mobile Banking,46877.06,...,0,Active,2023-01-22,Neha Sharma,Female,41,Teacher,831421,Kolkata,2020-08-18

In [37]:
master = master.merge(
    merchants,
    on="merchant_id",
    how="left"
)

master.head()

,transaction_id,account_id,merchant_id,branch_id,transaction_datetime,transaction_type,amount,payment_method,channel,opening_balance,...,gender,age,occupation,annual_income,city_x,join_date,merchant_name,category,mcc_code,city_y
0,TXN0000001,ACC002975,MER104,BR025,2025-12-18 22:48:00,Debit,4086.42,UPI,Mobile Banking,85557.75,...,Female,54,Designer,445724,Bengaluru,2025-02-28,Shopping Store 104,Shopping,5976,Ahmedabad
1,TXN0000002,ACC004775,MER002,BR023,2025-05-18 10:37:00,Credit,1793.55,UPI,Internet Banking,105884.92,...,Female,51,Analyst,865371,Kochi,2024-04-13,Flipkart,Shopping,5311,Surat
2,TXN0000003,ACC005627,MER009,BR019,2026-04-13 02:32:00,Debit,9547.04,NEFT,Internet Banking,336343.50,...,Female,34,Doctor,2423909,Kochi,2025-04-17,Uber,Travel,4121,Ranchi
3,TXN0000004,ACC002167,MER006,BR005,2025-06-12 18:22:00,Debit,764.22,UPI,ATM,96423.36,...,Female,28,Engineer,1595354,Noida,2023-12-11,Swiggy,Food,5812,Raipur
4,TXN0000005,ACC005845,MER085,BR010,2026-05-01 16:42:00,Debit,2599.33,Debit Card,Mobile Banking,46877.06,...,Female,41,Teacher,831421,Kolkata,2020-08-18,Healthcare Store 85,Healthcare,5764,Bhopal

In [38]:
master = master.merge(
    branches,
    on="branch_id",
    how="left"
)

master.head()

,transaction_id,account_id,merchant_id,branch_id,transaction_datetime,transaction_type,amount,payment_method,channel,opening_balance,...,annual_income,city_x,join_date,merchant_name,category,mcc_code,city_y,branch_name,city,region
0,TXN0000001,ACC002975,MER104,BR025,2025-12-18 22:48:00,Debit,4086.42,UPI,Mobile Banking,85557.75,...,445724,Bengaluru,2025-02-28,Shopping Store 104,Shopping,5976,Ahmedabad,Vellore Branch,Vellore,South
1,TXN0000002,ACC004775,MER002,BR023,2025-05-18 10:37:00,Credit,1793.55,UPI,Internet Banking,105884.92,...,865371,Kochi,2024-04-13,Flipkart,Shopping,5311,Surat,Indore Branch,Indore,Central
2,TXN0000003,ACC005627,MER009,BR019,2026-04-13 02:32:00,Debit,9547.04,NEFT,Internet Banking,336343.50,...,2423909,Kochi,2025-04-17,Uber,Travel,4121,Ranchi,Ranchi Branch,Ranchi,East
3,TXN0000004,ACC002167,MER006,BR005,2025-06-12 18:22:00,Debit,764.22,UPI,ATM,96423.36,...,1595354,Noida,2023-12-11,Swiggy,Food,5812,Raipur,Coimbatore Branch,Coimbatore,South
4,TXN0000005,ACC005845,MER085,BR010,2026-05-01 16:42:00,Debit,2599.33,Debit Card,Mobile Banking,46877.06,...,831421,Kolkata,2020-08-18,Healthcare Store 85,Healthcare,5764,Bhopal,Jaipur Branch,Jaipur,West

In [40]:
master.shape

(100000, 33)

In [41]:
master.columns.tolist()

['transaction_id',
 'account_id',
 'merchant_id',
 'branch_id',
 'transaction_datetime',
 'transaction_type',
 'amount',
 'payment_method',
 'channel',
 'opening_balance',
 'closing_balance',
 'status_x',
 'reference_no',
 'customer_id',
 'account_type',
 'balance',
 'credit_limit',
 'status_y',
 'opened_date',
 'name',
 'gender',
 'age',
 'occupation',
 'annual_income',
 'city_x',
 'join_date',
 'merchant_name',
 'category',
 'mcc_code',
 'city_y',
 'branch_name',
 'city',
 'region']

# Merges created duplicate columns because Accounts and Transactions both have status, and Customers and Merchants both have city. So we need to cleanup the duplicates.

In [43]:
master[["status_y"]].head()

  status_y
0   Active
1   Active
2   Active
3   Active
4   Active

In [44]:
master[["status_x"]].head()

  status_x
0  Success
1  Success
2  Success
3  Success
4  Success

In [45]:
master[["city_x"]].head()

      city_x
0  Bengaluru
1      Kochi
2      Kochi
3      Noida
4    Kolkata

In [46]:
master[["city_y"]].head()

      city_y
0  Ahmedabad
1      Surat
2     Ranchi
3     Raipur
4     Bhopal

In [47]:
master.rename(columns={
    "status_x": "transaction_status",
    "status_y": "account_status",
    "city_x": "customer_city",
    "city_y": "merchant_city"
}, inplace=True)

In [48]:
[col for col in master.columns if "_x" in col or "_y" in col]

[]

In [49]:
master.shape
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 33 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        100000 non-null  str
 1   account_id            100000 non-null  str
 2   merchant_id           100000 non-null  str
 3   branch_id             100000 non-null  str
 4   transaction_datetime  100000 non-null  datetime64[us]
 5   transaction_type      100000 non-null  str
 6   amount                100000 non-null  float64
 7   payment_method        100000 non-null  str
 8   channel               100000 non-null  str
 9   opening_balance       100000 non-null  float64
 10  closing_balance       100000 non-null  float64
 11  transaction_status    100000 non-null  str
 12  reference_no          100000 non-null  str
 13  customer_id           100000 non-null  str
 14  account_type          100000 non-null  str
 15  balance               100000 non-null  float64
 16  credit_limit          100000 non-null  int64
 17  account_status        100000 non-null  str
 18  opened_date           100000 non-null  str
 19  name                  100000 non-null  str
 20  gender                100000 non-null  str
 21  age                   100000 non-null  int64
 22  occupation            100000 non-null  str
 23  annual_income         100000 non-null  int64
 24  customer_city         100000 non-null  str
 25  join_date             100000 non-null  str
 26  merchant_name         100000 non-null  str
 27  category              100000 non-null  str
 28  mcc_code              100000 non-null  int64
 29  merchant_city         100000 non-null  str
 30  branch_name           100000 non-null  str
 31  city                  100000 non-null  str
 32  region                100000 non-null  str
dtypes: datetime64[us](1), float64(4), int64(4), str(24)
memory usage: 16.0 MB

Feature Engineering

In [51]:
# Date Features

master["year"] = master["transaction_datetime"].dt.year

master["month"] = master["transaction_datetime"].dt.month_name()

master["month_no"] = master["transaction_datetime"].dt.month

master["quarter"] = "Q" + master["transaction_datetime"].dt.quarter.astype(str)

master["day"] = master["transaction_datetime"].dt.day

master["weekday"] = master["transaction_datetime"].dt.day_name()

master["hour"] = master["transaction_datetime"].dt.hour

In [52]:
master[
    ["transaction_datetime",
     "year",
     "month",
     "quarter",
     "weekday",
     "hour"]
].head()

  transaction_datetime  year     month quarter   weekday  hour
0  2025-12-18 22:48:00  2025  December      Q4  Thursday    22
1  2025-05-18 10:37:00  2025       May      Q2    Sunday    10
2  2026-04-13 02:32:00  2026     April      Q2    Monday     2
3  2025-06-12 18:22:00  2025      June      Q2  Thursday    18
4  2026-05-01 16:42:00  2026       May      Q2    Friday    16

In [53]:
# Create a weekend flag as banks check for weekend or weekdays

In [54]:
master["is_weekend"] = master["weekday"].isin([
    "Saturday",
    "Sunday"
])

In [55]:
master[["weekday", "is_weekend"]].head()

    weekday  is_weekend
0  Thursday       False
1    Sunday        True
2    Monday       False
3  Thursday       False
4    Friday       False

In [56]:
# Revenue classification column
master["transaction_band"] = pd.cut(
    master["amount"],
    bins=[0,1000,5000,10000,50000,np.inf],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High",
        "Premium"
    ]
)

In [57]:
master["transaction_band"].value_counts()

transaction_band
Medium       58106
Low          29245
High          9194
Very High     2082
Premium       1373
Name: count, dtype: int64

In [58]:
master.shape

(100000, 42)

In [59]:
master.isnull().sum().sum()

np.int64(0)

In [60]:
master.head(3)

,transaction_id,account_id,merchant_id,branch_id,transaction_datetime,transaction_type,amount,payment_method,channel,opening_balance,...,region,year,month,month_no,quarter,day,weekday,hour,is_weekend,transaction_band
0,TXN0000001,ACC002975,MER104,BR025,2025-12-18 22:48:00,Debit,4086.42,UPI,Mobile Banking,85557.75,...,South,2025,December,12,Q4,18,Thursday,22,False,Medium
1,TXN0000002,ACC004775,MER002,BR023,2025-05-18 10:37:00,Credit,1793.55,UPI,Internet Banking,105884.92,...,Central,2025,May,5,Q2,18,Sunday,10,True,Medium
2,TXN0000003,ACC005627,MER009,BR019,2026-04-13 02:32:00,Debit,9547.04,NEFT,Internet Banking,336343.50,...,East,2026,April,4,Q2,13,Monday,2,False,High

Saving the Cleaned dataset

In [61]:
# Export the final analytical dataset
master.to_csv("banking_master.csv", index=False)

print("banking_master.csv exported successfully!")

banking_master.csv exported successfully!